// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://yahklrpcufpqccnnqryx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhaGtscnBjdWZwcWNjbm5xcnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzYyMzMsImV4cCI6MjA3MTE1MjIzM30.ouc-i_iq0S1qelfMIOGBWKBVkL-pB5sywPVBzINvWdI";

// Site URL configuration - change this for production
const SITE_URL = import.meta.env.VITE_SITE_URL || 'https://www.babilai.in';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    redirectTo: `${SITE_URL}/auth/callback`
  }
});